### PR TITLE
review TC

### PR DESCRIPTION
**Pull request by thijscobben**

### CODE REVIEW

**Comment by thijscobben** [comment]
Hi,

It would help if we create a sample of usage.

E.g.:
ibc = IrodsB2ShareClient(parameters)
ibc.create_draft(...)
ibc.add_data_to_draft(...)

It is not completely clear how the irods side works and what order of commands you imagined there.
Maybe in general it would be good to separate irods and b2share facing actions by e.g. moving those codes to two helper classes e.g.
from irods_collection import IrodsCollection
from b2share_record import B2ShareRecord

self.api_token = config.api_token
self.record = B2ShareRecord(user_id, community_id, ...)
self.collection = IrodsCollection(path, ...)

self.record.get_draft_url(...)
self.collection.size   (implemented as property eg. https://www.python-course.eu/python3_properties.php ? or with __attr__ 
or self.collection.size() and then it will call def size(self):

**Comment by thijscobben** [comment]
maybe even

in IrodsClient:
self.session = IRodsSession(...)

self.collection = IRodsCollection(session = self.session)

Later you could have a "manager" that can have a collections attribute that share a reference to the (stateless) irods session instance.

**Comment by chStaiger** [comment]
Many thanks for your feedback. I created the workflow file and finished the first version of all necessary functions. Now let's redistribute.

**Comment by chStaiger** [comment]
Hi Thijs, 

I reorganised my classes a bit. Any feedback is welcome.

**Comment by chStaiger** [comment]
That is the metadata I can create in the B2SHARE training instance:
https://trng-b2share.eudat.eu/records/339d1fcd2ed549d6bf5dd5f24fca5685

**Comment by chStaiger** [comment]
Classes are somewhat better sorted. 
Two workflows added.
Needs more testing.

**Pull request merged**
